// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGCco01ZW66YP4L9t_hGZjqP-Q1wmRSvI',
    appId: '1:607850843500:android:f9b7fbf8203cbd4bc37749',
    messagingSenderId: '607850843500',
    projectId: 'aromex-4a032',
    storageBucket: 'aromex-4a032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6tIhrdzr1FCwUqtNeuRoLfukvyB1oPd8',
    appId: '1:607850843500:ios:ff40fb256478f43dc37749',
    messagingSenderId: '607850843500',
    projectId: 'aromex-4a032',
    storageBucket: 'aromex-4a032.firebasestorage.app',
    iosBundleId: 'com.example.pukhrajMobiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6tIhrdzr1FCwUqtNeuRoLfukvyB1oPd8',
    appId: '1:607850843500:ios:ff40fb256478f43dc37749',
    messagingSenderId: '607850843500',
    projectId: 'aromex-4a032',
    storageBucket: 'aromex-4a032.firebasestorage.app',
    iosBundleId: 'com.example.pukhrajMobiles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBIOfnJeKiwwH065Cjvbk95MVNCe9bj2c',
    appId: '1:607850843500:web:e98ae0953f9e8e49c37749',
    messagingSenderId: '607850843500',
    projectId: 'aromex-4a032',
    authDomain: 'aromex-4a032.firebaseapp.com',
    storageBucket: 'aromex-4a032.firebasestorage.app',
    measurementId: 'G-V4X2QQ57QP',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBIOfnJeKiwwH065Cjvbk95MVNCe9bj2c',
    appId: '1:607850843500:web:e98ae0953f9e8e49c37749',
    messagingSenderId: '607850843500',
    projectId: 'aromex-4a032',
    authDomain: 'aromex-4a032.firebaseapp.com',
    storageBucket: 'aromex-4a032.firebasestorage.app',
    measurementId: 'G-V4X2QQ57QP',
  );

}